### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by den747** [fvictorio/git-infer#4]
Hi, first of all thanks.

I use git for more than just code and sometimes files have spaces in the name. 
git-infer is ignoring everything after the space.

Examples:
`expample@example  /access/data/work   master ●  git add vorlagen/example\ example1.txt 
 example@example  /access/data/work   master ✚  git-infer
[master 4856ewd] Update vorlagen/example
 1 file changed, 1 insertion(+), 1 deletion(-)`

Greatings

**Comment by fvictorio** [comment]
Hi, thanks for reporting this. I'll take a look as soon as I can!
